Sys.setenv(JAVA_HOME='C:/Program Files/Java/jre1.8.0_211')
library(wordcloud)                              
library(KoNLP)                                  
library(RColorBrewer)                         
setwd("D:/source")
text <- readLines("./R/10장/mis_document.txt", encoding ="UTF-8" )   
buildDictionary(ext_dic = "woorimalsam")        
pal2 <- brewer.pal(8, "Dark2")                  
noun <- sapply(text,extractNoun, USE.NAMES=F)   
noun           
