---
title: "9장 지도와 데이터"
author: "신봉균 20191624"
date: "`r Sys.Date()`"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 연습문제 1-1

```{r}
library(ggmap)
library(ggplot2)
register_google(key = 'AIzaSyDRI065JSqKKXqcmVbZQ7GiNnoKp0dA0ys')

gc= geocode(enc2utf8('서울시청'))
cen= as.numeric(gc)        #경도와 위도 값을 center값으로 직접 입력
map <- get_googlemap(center=cen,
                     size = c(600,600),
                     maptype = 'roadmap') 		# 지도 생성
ggmap(map) 

```

## 연습문제 1-2

```{r}
gc= geocode(enc2utf8('금강산'))
cen= as.numeric(gc)        #경도와 위도 값을 center값으로 직접 입력
map <- get_googlemap(center=cen,
                     size = c(500,500),
                     zoom = 8,
                     maptype = 'hybrid') 		# 지도 생성
ggmap(map) 
```
## 연습문제 1-3

```{r}
gc= geocode(enc2utf8('강남역'))
cen= as.numeric(gc)        #경도와 위도 값을 center값으로 직접 입력
map <- get_googlemap(center=cen,
                     size = c(640,640),
                     zoom = 16,
                     maptype = 'roadmap') 		# 지도 생성
ggmap(map) 
```

## 연습문제 1-4
```{r}
cen = c(127.397692, 36.337058)        #경도와 위도 값을 center값으로 직접 입력
map <- get_googlemap(center=cen,
                     zoom = 9,
                     maptype = 'roadmap') 		# 지도 생성
ggmap(map) 
```

## 연습문제 1-5

```{r}
cen = c(135.502330, 34.693594)        #경도와 위도 값을 center값으로 직접 입력
map <- get_googlemap(center=cen,
                     zoom = 10,
                     maptype = 'roadmap') 		# 지도 생성
ggmap(map) 
```
## 연습문제 3번번
```{r}

# 광역시 이름과 주소 정보
cities = data.frame(
  name = c("서울특별시", "부산광역시", "대구광역시", "인천광역시", "광주광역시", "대전광역시", "울산광역시"),
  address = c("서울특별시", "부산광역시", "대구광역시", "인천광역시", "광주광역시", "대전광역시", "울산광역시")
)

# 각 광역시의 위치 정보 가져오기
a = geocode(cities$address)
cities$lon = a$lon
cities$lat = a$lat
cities

# 지도 이미지 다운로드
cen= c(mean(cities$lon), mean(cities$lat))
map = get_googlemap(center = cen,
                    zoom = 7,
                    size = c(640,640),
                    maptype = 'roadmap')

# 지도에 마커와 텍스트 추가하기
ggmap(map) +
  geom_text(data = cities, aes(x = lon, y = lat, label = name),
            color = "red", size = 3) +
  geom_point(data = cities, aes(x = lon, y = lat),
             color = "red", size = 3)





```

## 연습문제 5번

```{r}
# 패키지 설치 및 로드
library(treemap)

data("GNI2014")


# 북아메리카 대륙에 있는 나라 선택
df= GNI2014[which(GNI2014$continent=='North America'),]
df= df[,c(2,4)]

a= geocode(df$country)
df$lon = a$lon
df$lat= a$lat

cen= c(mean(df$lon), mean(df$lat)) ##지도의 중심정 계산
gc= data.frame(lon=df$lon, lat=df$lat)  #측정 위치 좌표값 데이터


#인구수를 원의 크기로 표시하기

map= get_googlemap(center = cen,           
                   maptype = 'roadmap',
                   zoom=3)

gmap= ggmap(map)

gmap+geom_point(data= df,
                aes(x=lon, y=lat, size=population),
                alpha=0.5,
                col='green')+
  scale_size_continuous(range=c(1,14))

```


## 연습문제 7번

```{r}
library(ggplot2)
library(ggmap)
getwd()
setwd("C:/Users/Sin/Desktop/coding_study/R")

register_google(key = 'AIzaSyDRI065JSqKKXqcmVbZQ7GiNnoKp0dA0ys')

monthly_accident = read.csv(file = "./데이터.csv", encoding = 'cp949')

myds <- aggregate(x = monthly_accident[monthly_accident[, "시도"] != "세종", "사망자수"],
                  by = list("시도" = monthly_accident[monthly_accident[, "시도"] != "세종",]$시도), 
                  FUN = sum)
names <- myds$시도
gc <- geocode(enc2utf8(names))
cen <- c(mean(gc$lon), mean(gc$lat))
df = data.frame(name = names, lon = gc$lon, lat = gc$lat, freq = myds$x)
map <- get_googlemap(center = cen, maptype = "roadmap", zoom = 7)
gmap <- ggmap(map)

gmap + geom_point(data = df, 
                  aes(x = lon, y = lat, size = freq), alpha = 0.3, col = "black") +
  scale_size_continuous(range = c(1, 14)) 


```































